import type { CardTypeId, EventTypeId, TemplateDefinition } from "@/types";
import { classicInvitation, profileCard, type Palette } from "@/templates/factory";

const gold: Palette = { paper: "#f7f1e6", ink: "#2b2118", accent: "#b08a4a", muted: "#7a6a55", line: "#d4c4a3" };
const ivory: Palette = { paper: "#fbf8f2", ink: "#1f1a16", accent: "#8c6d45", muted: "#6f6558", line: "#e2d5c0" };
const blush: Palette = { paper: "#f8eee9", ink: "#3d2a2d", accent: "#c27c8a", muted: "#8a6b70", line: "#e5cfcb" };
const ink: Palette = { paper: "#161412", ink: "#f4e7c8", accent: "#d4af37", muted: "#c9b896", line: "#3d3424" };
const marigold: Palette = { paper: "#fff6dc", ink: "#5c3b0a", accent: "#e8a317", muted: "#8a6418", line: "#efd28a" };
const sunset: Palette = { paper: "#fff1e0", ink: "#7c2d12", accent: "#ea580c", muted: "#9a3412", line: "#fdba74" };
const garden: Palette = { paper: "#eef5ea", ink: "#1f3324", accent: "#3f6b4a", muted: "#4f6554", line: "#c5d8c4" };
const night: Palette = { paper: "#1a1224", ink: "#f5e9ff", accent: "#f0b429", muted: "#c4b0d6", line: "#3d2d52" };
const fun: Palette = { paper: "#fff4e8", ink: "#9a3412", accent: "#f97316", muted: "#c2410c", line: "#fed7aa" };
const kids: Palette = { paper: "#e8f4ff", ink: "#0f2f5b", accent: "#2563eb", muted: "#3d5a80", line: "#93c5fd" };
const lamp: Palette = { paper: "#f6efe2", ink: "#3f2a14", accent: "#c4a35a", muted: "#7a6242", line: "#e0d0ae" };
const slate: Palette = { paper: "#f4f1ec", ink: "#171717", accent: "#44403c", muted: "#737373", line: "#d6d3d1" };
const folio: Palette = { paper: "#f8fafc", ink: "#0f172a", accent: "#1d4ed8", muted: "#475569", line: "#cbd5e1" };
const rose: Palette = { paper: "#fff1f2", ink: "#4c0519", accent: "#e11d48", muted: "#9f1239", line: "#fecdd3" };
const coral: Palette = { paper: "#fff7f5", ink: "#7f1d1d", accent: "#f43f5e", muted: "#9f1239", line: "#fecdd3" };
const turmeric: Palette = { paper: "#fffbeb", ink: "#713f12", accent: "#f59e0b", muted: "#a16207", line: "#fde68a" };
const jewel: Palette = { paper: "#0c1929", ink: "#fde68a", accent: "#38bdf8", muted: "#94a3b8", line: "#1e3a5f" };
const lavender: Palette = { paper: "#f5f0ff", ink: "#2e1065", accent: "#7c3aed", muted: "#6d28d9", line: "#ddd6fe" };
const champagne: Palette = { paper: "#faf6ef", ink: "#3f2e1e", accent: "#c9a66b", muted: "#8a7355", line: "#e8dcc8" };
const sage: Palette = { paper: "#f2f5f0", ink: "#1c2b1f", accent: "#5b7c65", muted: "#4a6352", line: "#c9d6cb" };
const inkBlue: Palette = { paper: "#0f172a", ink: "#e2e8f0", accent: "#38bdf8", muted: "#94a3b8", line: "#1e293b" };
const peach: Palette = { paper: "#fff5ee", ink: "#7c2d12", accent: "#ea8a5e", muted: "#9a5b3c", line: "#ffd7c2" };

const PLAYFAIR = '"Playfair Display", Georgia, serif';
const CORMORANT = '"Cormorant Garamond", Georgia, serif';
const INTER = "Inter, system-ui, sans-serif";
const SCRIPT = '"Great Vibes", cursive';

const ALL_EVENTS: EventTypeId[] = [
  "wedding",
  "engagement",
  "birthday",
  "gruha-pravesham",
  "sangeet",
  "haldi",
  "baby-shower",
  "anniversary",
  "reception",
  "housewarming",
  "naming-ceremony",
  "mehendi",
  "save-the-date",
  "party",
  "custom",
];

export const TEMPLATES: TemplateDefinition[] = [
  classicInvitation({
    id: "royal-gold",
    name: "Royal Gold",
    category: "royal",
    tags: ["wedding", "luxury", "traditional", "elegant"],
    eventTypes: ["wedding", "reception", "engagement"],
    palette: gold,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "centered",
  }),
  classicInvitation({
    id: "ivory-lotus-quiet",
    name: "Ivory Lotus",
    category: "minimal",
    tags: ["wedding", "minimal", "south-indian", "trending"],
    eventTypes: ["wedding", "engagement", "reception"],
    palette: { paper: "#fbf8f2", ink: "#1f1a16", accent: "#b08a4a", muted: "#6f6558", line: "#e8dcc8" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "lotus",
    layout: "centered",
  }),
  classicInvitation({
    id: "south-indian-classic",
    name: "South Indian Classic",
    category: "south-indian",
    tags: ["wedding", "telugu", "tamil", "traditional"],
    eventTypes: ["wedding", "reception"],
    palette: lamp,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "mandala",
    layout: "traditional",
  }),
  classicInvitation({
    id: "nakshatra-night",
    name: "Nakshatra Night",
    category: "celestial",
    tags: ["wedding", "reception", "celestial", "trending"],
    eventTypes: ["wedding", "reception", "anniversary", "engagement"],
    palette: { paper: "#0b1020", ink: "#e8eefc", accent: "#c4b5fd", muted: "#94a3b8", line: "#1e293b" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "dots",
    layout: "dark",
  }),
  classicInvitation({
    id: "botanical-wild",
    name: "Botanical Wild",
    category: "floral",
    tags: ["wedding", "garden", "botanical", "trending"],
    eventTypes: ["wedding", "engagement", "anniversary", "party"],
    palette: garden,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "floral",
    layout: "vine",
  }),
  classicInvitation({
    id: "monogram-quiet",
    name: "Monogram Quiet",
    category: "minimal",
    tags: ["engagement", "minimal", "modern", "trending"],
    eventTypes: ["engagement", "save-the-date", "wedding"],
    palette: champagne,
    heading: PLAYFAIR,
    body: INTER,
    motif: "border",
    layout: "centered",
  }),
  classicInvitation({
    id: "dusty-sage",
    name: "Dusty Sage",
    category: "minimal",
    tags: ["wedding", "minimal", "pastel", "trending"],
    eventTypes: ["wedding", "engagement", "anniversary"],
    palette: sage,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "lotus",
    layout: "arch",
  }),
  classicInvitation({
    id: "burgundy-cinema",
    name: "Burgundy Cinema",
    category: "luxury",
    tags: ["reception", "dark", "cinematic", "trending"],
    eventTypes: ["reception", "party", "anniversary", "sangeet"],
    palette: { paper: "#1a0b10", ink: "#fce7f3", accent: "#fb7185", muted: "#f9a8d4", line: "#4c0519" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "dark",
  }),
  classicInvitation({
    id: "kolam-line",
    name: "Kolam Line",
    category: "cultural",
    tags: ["wedding", "south-indian", "minimal", "trending"],
    eventTypes: ["wedding", "gruha-pravesham", "naming-ceremony"],
    palette: { paper: "#fffdf8", ink: "#292524", accent: "#a16207", muted: "#78716c", line: "#e7e5e4" },
    heading: PLAYFAIR,
    body: INTER,
    motif: "mandala",
    layout: "traditional",
  }),
  classicInvitation({
    id: "modern-minimal-invite",
    name: "Modern Line",
    category: "minimal",
    tags: ["engagement", "modern", "split"],
    eventTypes: ["engagement", "save-the-date", "custom"],
    palette: slate,
    heading: INTER,
    body: INTER,
    motif: "border",
    layout: "split",
  }),
  classicInvitation({
    id: "birthday-color",
    name: "Birthday Color",
    category: "colorful",
    tags: ["birthday", "fun", "festive", "colorful"],
    eventTypes: ["birthday", "party"],
    palette: fun,
    heading: PLAYFAIR,
    body: INTER,
    motif: "dots",
    layout: "festive",
  }),
  classicInvitation({
    id: "birthday-luxury",
    name: "Midnight Toast",
    category: "luxury",
    tags: ["birthday", "adult", "dark", "elegant"],
    eventTypes: ["birthday", "anniversary", "party"],
    palette: ink,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "dark",
  }),
  classicInvitation({
    id: "birthday-kids",
    name: "Sky Party",
    category: "kids",
    tags: ["birthday", "kids", "colorful", "festive"],
    eventTypes: ["birthday", "naming-ceremony", "baby-shower"],
    palette: kids,
    heading: CORMORANT,
    body: INTER,
    motif: "dots",
    layout: "festive",
  }),
  classicInvitation({
    id: "gruha-lamp",
    name: "Deepam",
    category: "traditional",
    tags: ["gruha-pravesham", "telugu", "south-indian", "traditional"],
    eventTypes: ["gruha-pravesham", "housewarming", "naming-ceremony"],
    palette: lamp,
    heading: PLAYFAIR,
    body: INTER,
    motif: "lamp",
    layout: "traditional",
  }),
  classicInvitation({
    id: "gruha-modern",
    name: "New Threshold",
    category: "modern",
    tags: ["gruha-pravesham", "minimal", "modern"],
    eventTypes: ["gruha-pravesham", "housewarming"],
    palette: garden,
    heading: CORMORANT,
    body: INTER,
    motif: "border",
    layout: "split",
  }),
  classicInvitation({
    id: "sangeet-royal",
    name: "Sangeet Court",
    category: "royal",
    tags: ["sangeet", "festive", "royal", "dark"],
    eventTypes: ["sangeet", "reception"],
    palette: night,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "dark",
  }),
  classicInvitation({
    id: "sangeet-night",
    name: "Bollywood Night",
    category: "festive",
    tags: ["sangeet", "dark", "festive", "colorful"],
    eventTypes: ["sangeet", "party"],
    palette: jewel,
    heading: CORMORANT,
    body: INTER,
    motif: "dots",
    layout: "dark",
  }),
  classicInvitation({
    id: "haldi-sun",
    name: "Haldi Sun",
    category: "yellow",
    tags: ["haldi", "floral", "festive", "colorful"],
    eventTypes: ["haldi", "mehendi"],
    palette: marigold,
    heading: PLAYFAIR,
    body: INTER,
    motif: "sun",
    layout: "festive",
  }),
  classicInvitation({
    id: "haldi-marigold",
    name: "Marigold Morning",
    category: "traditional",
    tags: ["haldi", "traditional", "floral", "photo"],
    eventTypes: ["haldi", "mehendi"],
    palette: turmeric,
    heading: CORMORANT,
    body: INTER,
    motif: "floral",
    layout: "banner",
  }),
  classicInvitation({
    id: "universal-editorial",
    name: "Editorial Cream",
    category: "elegant",
    tags: ["custom", "party", "save-the-date", "elegant"],
    eventTypes: ALL_EVENTS,
    palette: ivory,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "border",
    layout: "centered",
  }),
  classicInvitation({
    id: "coral-celebration",
    name: "Coral Celebration",
    category: "colorful",
    tags: ["party", "birthday", "anniversary", "colorful", "festive"],
    eventTypes: ["party", "birthday", "anniversary", "baby-shower"],
    palette: coral,
    heading: PLAYFAIR,
    body: INTER,
    motif: "floral",
    layout: "photo",
  }),
  classicInvitation({
    id: "garden-vow",
    name: "Garden Vow",
    category: "floral",
    tags: ["wedding", "floral", "garden", "elegant"],
    eventTypes: ["wedding", "engagement", "anniversary"],
    palette: garden,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "floral",
    layout: "vine",
  }),
  classicInvitation({
    id: "sunset-haldi",
    name: "Sunset Haldi",
    category: "festive",
    tags: ["haldi", "festive", "colorful", "photo"],
    eventTypes: ["haldi", "mehendi", "sangeet"],
    palette: sunset,
    heading: PLAYFAIR,
    body: INTER,
    motif: "sun",
    layout: "photo",
  }),
  classicInvitation({
    id: "midnight-vow",
    name: "Midnight Vow",
    category: "luxury",
    tags: ["wedding", "dark", "elegant", "royal"],
    eventTypes: ["wedding", "reception", "anniversary"],
    palette: ink,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "dark",
  }),
  classicInvitation({
    id: "champagne-linen",
    name: "Champagne Linen",
    category: "elegant",
    tags: ["wedding", "engagement", "elegant", "minimal"],
    eventTypes: ["wedding", "engagement", "save-the-date"],
    palette: champagne,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "border",
    layout: "arch",
  }),
  classicInvitation({
    id: "sage-reception",
    name: "Sage Reception",
    category: "minimal",
    tags: ["reception", "minimal", "garden"],
    eventTypes: ["reception", "anniversary", "party"],
    palette: sage,
    heading: PLAYFAIR,
    body: INTER,
    motif: "border",
    layout: "split",
  }),
  classicInvitation({
    id: "sapphire-soirée",
    name: "Sapphire Soirée",
    category: "royal",
    tags: ["party", "reception", "dark", "royal"],
    eventTypes: ["party", "reception", "sangeet"],
    palette: inkBlue,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "dark",
  }),
  classicInvitation({
    id: "paper-crest",
    name: "Paper Crest",
    category: "traditional",
    tags: ["wedding", "traditional", "elegant"],
    eventTypes: ["wedding", "engagement", "anniversary"],
    palette: ivory,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "mandala",
    layout: "traditional",
  }),
  // —— Expanded event styles: royal / traditional / cultural / aesthetic ——
  classicInvitation({
    id: "maharaja-gold",
    name: "Maharaja Gold",
    category: "royal",
    tags: ["wedding", "royal", "luxury"],
    eventTypes: ["wedding", "reception"],
    palette: gold,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "royal",
  }),
  classicInvitation({
    id: "lotus-blessing",
    name: "Lotus Blessing",
    category: "cultural",
    tags: ["wedding", "cultural", "traditional"],
    eventTypes: ["wedding", "engagement", "naming-ceremony"],
    palette: lamp,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "lotus",
    layout: "cultural",
  }),
  classicInvitation({
    id: "north-indian-heritage",
    name: "North Indian Heritage",
    category: "traditional",
    tags: ["wedding", "cultural", "traditional"],
    eventTypes: ["wedding", "reception", "sangeet"],
    palette: { paper: "#f9f0e4", ink: "#3b2114", accent: "#b45309", muted: "#7c4a2d", line: "#e7d2b8" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "paisley",
    layout: "traditional",
  }),
  classicInvitation({
    id: "ring-atelier",
    name: "Ring Atelier",
    category: "elegant",
    tags: ["engagement", "elegant", "minimal"],
    eventTypes: ["engagement", "save-the-date"],
    palette: champagne,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "royal",
  }),
  classicInvitation({
    id: "kundan-glow",
    name: "Kundan Glow",
    category: "cultural",
    tags: ["engagement", "cultural", "royal"],
    eventTypes: ["engagement", "wedding", "mehendi"],
    palette: { paper: "#1c1410", ink: "#fde68a", accent: "#f59e0b", muted: "#d6b37a", line: "#3f2e1e" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "paisley",
    layout: "cultural",
  }),
  classicInvitation({
    id: "carnival-confetti",
    name: "Carnival Confetti",
    category: "festive",
    tags: ["birthday", "festive", "colorful"],
    eventTypes: ["birthday", "party"],
    palette: { paper: "#fff7ed", ink: "#9a3412", accent: "#fb923c", muted: "#c2410c", line: "#fed7aa" },
    heading: PLAYFAIR,
    body: INTER,
    motif: "dots",
    layout: "festive",
  }),
  classicInvitation({
    id: "velvet-year",
    name: "Velvet Year",
    category: "royal",
    tags: ["birthday", "royal", "elegant"],
    eventTypes: ["birthday", "anniversary"],
    palette: { paper: "#1a0b14", ink: "#fce7f3", accent: "#f472b6", muted: "#f9a8d4", line: "#4a1834" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "royal",
  }),
  classicInvitation({
    id: "storybook-day",
    name: "Storybook Day",
    category: "aesthetic",
    tags: ["birthday", "kids", "aesthetic"],
    eventTypes: ["birthday", "baby-shower", "naming-ceremony"],
    palette: { paper: "#f0f9ff", ink: "#0c4a6e", accent: "#38bdf8", muted: "#0369a1", line: "#bae6fd" },
    heading: CORMORANT,
    body: INTER,
    motif: "sun",
    layout: "banner",
  }),
  classicInvitation({
    id: "vastu-lotus",
    name: "Vastu Lotus",
    category: "cultural",
    tags: ["gruha-pravesham", "cultural", "traditional"],
    eventTypes: ["gruha-pravesham", "housewarming"],
    palette: lamp,
    heading: PLAYFAIR,
    body: INTER,
    motif: "lotus",
    layout: "cultural",
  }),
  classicInvitation({
    id: "home-hearth",
    name: "Home & Hearth",
    category: "traditional",
    tags: ["gruha-pravesham", "traditional", "warm"],
    eventTypes: ["gruha-pravesham", "housewarming", "naming-ceremony"],
    palette: { paper: "#faf4eb", ink: "#3f2a14", accent: "#a16207", muted: "#78716c", line: "#e7d8c3" },
    heading: CORMORANT,
    body: INTER,
    motif: "lamp",
    layout: "traditional",
  }),
  classicInvitation({
    id: "open-doors",
    name: "Open Doors",
    category: "modern",
    tags: ["housewarming", "modern", "minimal"],
    eventTypes: ["housewarming", "gruha-pravesham", "party"],
    palette: sage,
    heading: INTER,
    body: INTER,
    motif: "border",
    layout: "split",
  }),
  classicInvitation({
    id: "raas-royale",
    name: "Raas Royale",
    category: "royal",
    tags: ["sangeet", "royal", "festive"],
    eventTypes: ["sangeet", "reception"],
    palette: night,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "royal",
  }),
  classicInvitation({
    id: "dhol-night",
    name: "Dhol Night",
    category: "festive",
    tags: ["sangeet", "festive", "cultural"],
    eventTypes: ["sangeet", "party", "mehendi"],
    palette: { paper: "#2a1020", ink: "#ffe4e6", accent: "#fb7185", muted: "#fda4af", line: "#4c1d2a" },
    heading: CORMORANT,
    body: INTER,
    motif: "paisley",
    layout: "festive",
  }),
  classicInvitation({
    id: "haldi-palace",
    name: "Haldi Palace",
    category: "royal",
    tags: ["haldi", "royal", "festive"],
    eventTypes: ["haldi", "mehendi"],
    palette: marigold,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "sun",
    layout: "royal",
  }),
  classicInvitation({
    id: "turmeric-trail",
    name: "Turmeric Trail",
    category: "cultural",
    tags: ["haldi", "cultural", "traditional"],
    eventTypes: ["haldi", "mehendi", "sangeet"],
    palette: turmeric,
    heading: CORMORANT,
    body: INTER,
    motif: "paisley",
    layout: "cultural",
  }),
  classicInvitation({
    id: "mehendi-moon",
    name: "Mehendi Moon",
    category: "aesthetic",
    tags: ["mehendi", "aesthetic", "elegant"],
    eventTypes: ["mehendi", "engagement"],
    palette: lavender,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "lotus",
    layout: "banner",
  }),
  classicInvitation({
    id: "soft-arrival",
    name: "Soft Arrival",
    category: "aesthetic",
    tags: ["baby-shower", "aesthetic", "pastel"],
    eventTypes: ["baby-shower", "naming-ceremony"],
    palette: peach,
    heading: CORMORANT,
    body: INTER,
    motif: "floral",
    layout: "centered",
  }),
  classicInvitation({
    id: "little-lotus",
    name: "Little Lotus",
    category: "cultural",
    tags: ["naming-ceremony", "cultural", "traditional"],
    eventTypes: ["naming-ceremony", "baby-shower"],
    palette: { paper: "#fff7ed", ink: "#7c2d12", accent: "#ea580c", muted: "#9a3412", line: "#fed7aa" },
    heading: PLAYFAIR,
    body: INTER,
    motif: "lotus",
    layout: "cultural",
  }),
  classicInvitation({
    id: "cradle-song",
    name: "Cradle Song",
    category: "elegant",
    tags: ["baby-shower", "elegant", "pastel"],
    eventTypes: ["baby-shower", "birthday"],
    palette: { paper: "#fdf4ff", ink: "#581c87", accent: "#c084fc", muted: "#7e22ce", line: "#e9d5ff" },
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "floral",
    layout: "photo",
  }),
  classicInvitation({
    id: "silver-chapter",
    name: "Silver Chapter",
    category: "elegant",
    tags: ["anniversary", "elegant", "minimal"],
    eventTypes: ["anniversary", "reception"],
    palette: { paper: "#f8fafc", ink: "#0f172a", accent: "#64748b", muted: "#475569", line: "#cbd5e1" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "border",
    layout: "centered",
  }),
  classicInvitation({
    id: "golden-years",
    name: "Golden Years",
    category: "royal",
    tags: ["anniversary", "royal", "luxury"],
    eventTypes: ["anniversary", "wedding"],
    palette: gold,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "royal",
  }),
  classicInvitation({
    id: "grand-soirée",
    name: "Grand Soirée",
    category: "royal",
    tags: ["reception", "royal", "dark"],
    eventTypes: ["reception", "party", "anniversary"],
    palette: ink,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "diamond",
    layout: "royal",
  }),
  classicInvitation({
    id: "save-date-serif",
    name: "Save the Serif",
    category: "minimal",
    tags: ["save-the-date", "minimal", "elegant"],
    eventTypes: ["save-the-date", "engagement", "wedding"],
    palette: slate,
    heading: PLAYFAIR,
    body: INTER,
    motif: "border",
    layout: "centered",
  }),
  classicInvitation({
    id: "calendar-bloom",
    name: "Calendar Bloom",
    category: "floral",
    tags: ["save-the-date", "floral", "aesthetic"],
    eventTypes: ["save-the-date", "engagement"],
    palette: blush,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "floral",
    layout: "photo",
  }),
  classicInvitation({
    id: "neon-gathering",
    name: "Neon Gathering",
    category: "festive",
    tags: ["party", "festive", "modern"],
    eventTypes: ["party", "birthday", "sangeet"],
    palette: jewel,
    heading: INTER,
    body: INTER,
    motif: "dots",
    layout: "dark",
  }),
  classicInvitation({
    id: "custom-atelier",
    name: "Custom Atelier",
    category: "elegant",
    tags: ["custom", "elegant", "minimal"],
    eventTypes: ["custom", "party", "save-the-date"],
    palette: champagne,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "border",
    layout: "arch",
  }),
  classicInvitation({
    id: "custom-folk",
    name: "Custom Folk",
    category: "cultural",
    tags: ["custom", "cultural", "traditional"],
    eventTypes: ALL_EVENTS,
    palette: { paper: "#fffbeb", ink: "#422006", accent: "#d97706", muted: "#92400e", line: "#fde68a" },
    heading: CORMORANT,
    body: INTER,
    motif: "paisley",
    layout: "cultural",
  }),
  classicInvitation({
    id: "vineyard-vow",
    name: "Vineyard Vow",
    category: "floral",
    tags: ["wedding", "floral", "vine"],
    eventTypes: ["wedding", "anniversary", "engagement"],
    palette: sage,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "floral",
    layout: "vine",
  }),
  classicInvitation({
    id: "archway-ivory",
    name: "Archway Ivory",
    category: "elegant",
    tags: ["wedding", "elegant", "arch"],
    eventTypes: ["wedding", "reception", "engagement"],
    palette: ivory,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "lotus",
    layout: "arch",
  }),
  classicInvitation({
    id: "scallop-romance",
    name: "Scallop Romance",
    category: "aesthetic",
    tags: ["engagement", "lace", "elegant"],
    eventTypes: ["engagement", "anniversary", "wedding"],
    palette: blush,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "floral",
    layout: "lace",
  }),
  classicInvitation({
    id: "marigold-garland",
    name: "Marigold Garland",
    category: "festive",
    tags: ["haldi", "garland", "festive"],
    eventTypes: ["haldi", "mehendi", "sangeet"],
    palette: marigold,
    heading: PLAYFAIR,
    body: INTER,
    motif: "sun",
    layout: "garland",
  }),
  classicInvitation({
    id: "peacock-sangeet",
    name: "Peacock Sangeet",
    category: "cultural",
    tags: ["sangeet", "peacock", "festive"],
    eventTypes: ["sangeet", "reception", "party"],
    palette: night,
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "paisley",
    layout: "mehendi",
  }),
  classicInvitation({
    id: "lace-anniversary",
    name: "Lace Anniversary",
    category: "elegant",
    tags: ["anniversary", "lace", "elegant"],
    eventTypes: ["anniversary", "wedding"],
    palette: champagne,
    heading: CORMORANT,
    body: INTER,
    accent: SCRIPT,
    motif: "border",
    layout: "lace",
  }),
  profileCard({
    id: "bio-elegant",
    name: "Classic Sheet",
    category: "elegant",
    cardTypes: ["bio", "family-intro", "personal-intro"],
    palette: { paper: "#ffffff", ink: "#3d3429", accent: "#5d4037", muted: "#6d5c50", line: "#5d4037" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  profileCard({
    id: "bio-royal",
    name: "Warm Classic",
    category: "elegant",
    cardTypes: ["bio", "family-intro"],
    palette: { paper: "#ffffff", ink: "#2a2118", accent: "#6b5344", muted: "#6b5a3e", line: "#d4c4a3" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  profileCard({
    id: "dating-modern",
    name: "Modern Dating",
    category: "modern",
    cardTypes: ["dating-bio", "birthday-profile", "custom-card"],
    palette: rose,
    heading: INTER,
    body: INTER,
    layout: "split",
  }),
  profileCard({
    id: "speaker-pro",
    name: "Speaker Folio",
    category: "professional",
    cardTypes: ["conference-speaker", "seminar-speaker", "professional", "event-host"],
    palette: folio,
    heading: PLAYFAIR,
    body: INTER,
    layout: "folio",
  }),
  profileCard({
    id: "speaker-clean",
    name: "Seminar Clean",
    category: "minimal",
    cardTypes: ["conference-speaker", "seminar-speaker", "professional"],
    palette: slate,
    heading: INTER,
    body: INTER,
    layout: "portrait",
  }),
  profileCard({
    id: "soft-circle",
    name: "Soft Circle",
    category: "elegant",
    cardTypes: ["personal-intro", "family-intro"],
    palette: blush,
    heading: CORMORANT,
    body: INTER,
    layout: "circle",
  }),
  profileCard({
    id: "bold-split",
    name: "Bold Split",
    category: "modern",
    cardTypes: ["dating-bio", "event-host", "custom-card", "birthday-profile"],
    palette: coral,
    heading: INTER,
    body: INTER,
    layout: "split",
  }),
  // —— Clean Bio Data sheets (Label : value — not resume layouts) ——
  profileCard({
    id: "bio-linen-editorial",
    name: "Linen Sheet",
    category: "elegant",
    cardTypes: ["bio"],
    palette: { paper: "#faf8f4", ink: "#2f2922", accent: "#5d4037", muted: "#7a6b5c", line: "#e2d5c0" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  profileCard({
    id: "bio-skyline-split",
    name: "Simple Sheet",
    category: "minimal",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#1c1917", accent: "#44403c", muted: "#57534e", line: "#e7e5e4" },
    heading: INTER,
    body: INTER,
    layout: "biodata-compact",
  }),
  profileCard({
    id: "bio-mist-spaced",
    name: "Ivory Formal",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#fffefb", ink: "#3a3228", accent: "#6b4f3a", muted: "#6d5c50", line: "#6b4f3a" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  profileCard({
    id: "bio-arch-formal",
    name: "Border Formal",
    category: "elegant",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#2c241c", accent: "#7a5c3e", muted: "#6d5c50", line: "#e8dcc8" },
    heading: INTER,
    body: INTER,
    layout: "biodata-compact",
  }),
  profileCard({
    id: "bio-garland-bloom",
    name: "Warm Sheet",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#fffdf8", ink: "#3f2a14", accent: "#9a6b3c", muted: "#7a6242", line: "#e0d0ae" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  profileCard({
    id: "bio-gold-frame",
    name: "Gold Sheet",
    category: "royal",
    cardTypes: ["bio"],
    palette: { paper: "#fffcf5", ink: "#2a2118", accent: "#b08a4a", muted: "#7a6a55", line: "#d4c4a3" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  profileCard({
    id: "bio-compact-sheet",
    name: "Compact Sheet",
    category: "minimal",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#171717", accent: "#44403c", muted: "#57534e", line: "#d6d3d1" },
    heading: INTER,
    body: INTER,
    layout: "biodata-compact",
  }),
  profileCard({
    id: "bio-sage-columns",
    name: "Sage Sheet",
    category: "elegant",
    cardTypes: ["bio"],
    palette: sage,
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  profileCard({
    id: "bio-navy-panel",
    name: "Navy Sheet",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#0f172a", accent: "#334155", muted: "#475569", line: "#94a3b8" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  profileCard({
    id: "bio-blush-modern",
    name: "Blush Sheet",
    category: "elegant",
    cardTypes: ["bio"],
    palette: { paper: "#fffaf8", ink: "#3d2a2d", accent: "#8b5e5e", muted: "#8a6b70", line: "#e5cfcb" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  profileCard({
    id: "bio-walnut-classic",
    name: "Walnut Classic",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#2c241c", accent: "#4e342e", muted: "#6d5c50", line: "#4e342e" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
  }),
  // —— No-photo clean sheets ——
  profileCard({
    id: "bio-plain-text",
    name: "Plain Text Sheet",
    category: "minimal",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#2c241c", accent: "#5d4037", muted: "#6d5c50", line: "#5d4037" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    withPhoto: false,
  }),
  profileCard({
    id: "bio-compact-nophoto",
    name: "Compact Text",
    category: "minimal",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#171717", accent: "#44403c", muted: "#57534e", line: "#d6d3d1" },
    heading: INTER,
    body: INTER,
    layout: "biodata-compact",
    withPhoto: false,
  }),
  // —— Emblem Bio Data sheets (decorative marks; neutral style names) ——
  profileCard({
    id: "bio-om-sheet",
    name: "Amber Emblem",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#3d3429", accent: "#8c6d45", muted: "#6f6558", line: "#d4c4a3" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "om",
    withPhoto: true,
  }),
  profileCard({
    id: "bio-om-text",
    name: "Amber Emblem Text",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#fffefb", ink: "#3d3429", accent: "#8c6d45", muted: "#6f6558", line: "#d4c4a3" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "om",
    withPhoto: false,
  }),
  profileCard({
    id: "bio-swastik-sheet",
    name: "Heritage Seal",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#5c3b0a", accent: "#b45309", muted: "#8a6418", line: "#fde68a" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "swastik",
    withPhoto: true,
  }),
  profileCard({
    id: "bio-swastik-text",
    name: "Heritage Seal Text",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#fffbeb", ink: "#5c3b0a", accent: "#b45309", muted: "#8a6418", line: "#fde68a" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "swastik",
    withPhoto: false,
  }),
  profileCard({
    id: "bio-krishna-sheet",
    name: "Feather Seal",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#1e3a5f", accent: "#1d4ed8", muted: "#475569", line: "#bfdbfe" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "krishna",
    withPhoto: true,
  }),
  profileCard({
    id: "bio-krishna-text",
    name: "Feather Seal Text",
    category: "traditional",
    cardTypes: ["bio"],
    palette: { paper: "#f8fafc", ink: "#1e3a5f", accent: "#1d4ed8", muted: "#475569", line: "#bfdbfe" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "krishna",
    withPhoto: false,
  }),
  profileCard({
    id: "bio-jesus-sheet",
    name: "Quiet Seal",
    category: "elegant",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#1f2937", accent: "#4b5563", muted: "#6b7280", line: "#d1d5db" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "cross",
    withPhoto: true,
  }),
  profileCard({
    id: "bio-jesus-text",
    name: "Quiet Seal Text",
    category: "elegant",
    cardTypes: ["bio"],
    palette: { paper: "#f9fafb", ink: "#1f2937", accent: "#4b5563", muted: "#6b7280", line: "#d1d5db" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "cross",
    withPhoto: false,
  }),
  profileCard({
    id: "bio-allah-sheet",
    name: "Garden Seal",
    category: "elegant",
    cardTypes: ["bio"],
    palette: { paper: "#ffffff", ink: "#14532d", accent: "#15803d", muted: "#4d7c5a", line: "#bbf7d0" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "crescent",
    withPhoto: true,
  }),
  profileCard({
    id: "bio-allah-text",
    name: "Garden Seal Text",
    category: "elegant",
    cardTypes: ["bio"],
    palette: { paper: "#f0fdf4", ink: "#14532d", accent: "#15803d", muted: "#4d7c5a", line: "#bbf7d0" },
    heading: INTER,
    body: INTER,
    layout: "biodata-classic",
    blessing: "crescent",
    withPhoto: false,
  }),
  // —— Cool light / spaced photography & collage (additive only) ——
  classicInvitation({
    id: "mist-portrait",
    name: "Mist Portrait",
    category: "minimal",
    tags: ["wedding", "photo", "minimal", "cool"],
    eventTypes: ["wedding", "engagement", "anniversary"],
    palette: { paper: "#f7f9fb", ink: "#1e293b", accent: "#64748b", muted: "#94a3b8", line: "#e2e8f0" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "border",
    layout: "photo-spaced",
  }),
  classicInvitation({
    id: "skyline-soft",
    name: "Skyline Soft",
    category: "minimal",
    tags: ["wedding", "photo", "cool", "light"],
    eventTypes: ["wedding", "reception", "save-the-date"],
    palette: { paper: "#f4f8fc", ink: "#0f172a", accent: "#7dd3fc", muted: "#64748b", line: "#e0f2fe" },
    heading: CORMORANT,
    body: INTER,
    motif: "border",
    layout: "photo-spaced",
  }),
  classicInvitation({
    id: "cloud-duo",
    name: "Cloud Duo",
    category: "collage",
    tags: ["engagement", "collage", "minimal", "cool"],
    eventTypes: ["engagement", "wedding", "anniversary"],
    palette: { paper: "#fafbfc", ink: "#334155", accent: "#94a3b8", muted: "#94a3b8", line: "#e2e8f0" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "border",
    layout: "collage-duo",
  }),
  classicInvitation({
    id: "frost-duo",
    name: "Frost Duo",
    category: "collage",
    tags: ["wedding", "collage", "cool", "light"],
    eventTypes: ["wedding", "engagement", "party"],
    palette: { paper: "#f8fafc", ink: "#1e293b", accent: "#a5b4fc", muted: "#64748b", line: "#e0e7ff" },
    heading: CORMORANT,
    body: INTER,
    motif: "border",
    layout: "collage-duo",
  }),
  classicInvitation({
    id: "air-trio",
    name: "Air Trio",
    category: "collage",
    tags: ["wedding", "collage", "minimal", "cool"],
    eventTypes: ["wedding", "engagement", "anniversary", "reception"],
    palette: { paper: "#f9fafb", ink: "#111827", accent: "#9ca3af", muted: "#6b7280", line: "#f3f4f6" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "border",
    layout: "collage-trio",
  }),
  classicInvitation({
    id: "linen-trio",
    name: "Linen Trio",
    category: "collage",
    tags: ["engagement", "collage", "light", "cool"],
    eventTypes: ["engagement", "save-the-date", "wedding"],
    palette: { paper: "#f7f6f4", ink: "#292524", accent: "#a8a29e", muted: "#78716c", line: "#e7e5e4" },
    heading: CORMORANT,
    body: INTER,
    motif: "border",
    layout: "collage-trio",
  }),
  classicInvitation({
    id: "magazine-grid",
    name: "Magazine Grid",
    category: "collage",
    tags: ["wedding", "collage", "grid", "minimal"],
    eventTypes: ["wedding", "reception", "party", "anniversary"],
    palette: { paper: "#ffffff", ink: "#18181b", accent: "#71717a", muted: "#a1a1aa", line: "#e4e4e7" },
    heading: INTER,
    body: INTER,
    motif: "border",
    layout: "collage-grid",
  }),
  classicInvitation({
    id: "polaroid-grid",
    name: "Polaroid Grid",
    category: "collage",
    tags: ["birthday", "party", "collage", "cool"],
    eventTypes: ["birthday", "party", "engagement", "wedding"],
    palette: { paper: "#f8fafc", ink: "#0f172a", accent: "#38bdf8", muted: "#64748b", line: "#e0f2fe" },
    heading: CORMORANT,
    body: INTER,
    motif: "dots",
    layout: "collage-polaroid",
  }),
  classicInvitation({
    id: "opal-space",
    name: "Opal Space",
    category: "minimal",
    tags: ["wedding", "photo-spaced", "cool", "light"],
    eventTypes: ["wedding", "engagement", "anniversary"],
    palette: { paper: "#f5f7fa", ink: "#1f2937", accent: "#c4b5fd", muted: "#9ca3af", line: "#ede9fe" },
    heading: PLAYFAIR,
    body: INTER,
    accent: SCRIPT,
    motif: "lotus",
    layout: "photo-spaced",
  }),
  classicInvitation({
    id: "seafoam-duo",
    name: "Seafoam Duo",
    category: "collage",
    tags: ["engagement", "collage", "cool", "minimal"],
    eventTypes: ["engagement", "wedding", "housewarming"],
    palette: { paper: "#f0fdfa", ink: "#134e4a", accent: "#5eead4", muted: "#5f7a76", line: "#ccfbf1" },
    heading: CORMORANT,
    body: INTER,
    motif: "border",
    layout: "collage-duo",
  }),
];

export function getTemplate(id: string): TemplateDefinition | undefined {
  return TEMPLATES.find((template) => template.id === id);
}

export function templatesForEvent(eventType: EventTypeId): TemplateDefinition[] {
  return TEMPLATES.filter((template) => template.kind === "invitation" && template.eventTypes.includes(eventType));
}

export function templatesForCard(cardType: CardTypeId): TemplateDefinition[] {
  return TEMPLATES.filter((template) => template.kind === "card" && template.cardTypes?.includes(cardType));
}
